CREATE EXTENSION CITEXT;

CREATE TYPE USER_ROLE AS ENUM ('ADMIN', 'MAINTENANCE_ADMIN', 'USER');
CREATE TYPE DIGITAL_TOOL_STATUS AS ENUM ('PUBLISHED', 'UNPUBLISHED');
CREATE TYPE PROJECT_RESPONSE_STATUS AS ENUM ('PUBLISHED', 'UNPUBLISHED');
CREATE TYPE RESPONSE_TYPES AS ENUM ('S3_OBJ', 'FILE_LOCAL');

CREATE TABLE USERS (
    ID varchar(80) PRIMARY KEY,
    NAME TEXT NOT NULL,
    EMAIL citext UNIQUE,
    PASSWORD varchar(200) DEFAULT NULL,
    DATE_CREATED timestamp(0) DEFAULT NULL,
    ROLE USER_ROLE DEFAULT 'USER'
);

CREATE TABLE DIGITAL_TOOLS (
    ID varchar(80) PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION varchar(200) DEFAULT NULL,
    TEMPLATE JSON NOT NULL,
    PRICING JSON NOT NULL,
    IMAGE varchar(100) DEFAULT NULL,
    STATUS DIGITAL_TOOL_STATUS DEFAULT NULL
);

CREATE TABLE PROJECT_RESPONSES (
    ID varchar(80) PRIMARY KEY,
    RESPONSE_TYPE RESPONSE_TYPES NOT NULL,
    LOCATION varchar(80) NOT NULL,
    CREATION_DATE timestamp(0) DEFAULT NULL,
    EXPIRY_DATE timestamp(0) DEFAULT NULL,
    STATUS PROJECT_RESPONSE_STATUS NOT NULL
);

CREATE TABLE PROJECTS (
    ID varchar(80) PRIMARY KEY,
    NAME TEXT NOT NULL,
    USER_ID varchar(80) NOT NULL,
    TOOL_ID varchar(80) NOT NULL,
    RESPONSE_ID varchar(80) NOT NULL

    CONSTRAINT PROJECT_USER_ID_fk FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PROJECT_TOOL_ID_fk FOREIGN KEY (TOOL_ID) REFERENCES DIGITAL_TOOLS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PROJECT_RESPONSE_ID_fk FOREIGN KEY (RESPONSE_ID) REFERENCES PROJECT_RESPONSES (ID) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE INDEX PROJECT_USER_ID_idx ON PROJECTS (USER_ID);
